---
language: php
sudo: false
env:
  global:
    - GH_REF: github.com/shrikeh/teapot.git
    - secure: "h8Q6F3ThS/pwBDMUg3Vj5zKqVhk2Birt1cZkbIxiFOMI2ptKHg+j6m9n3HTMRZq1jdEUrqnbqME3cCAAIs70dvw24ByeS7GJxzaBNLf/uA2nt6+6BiGvbAUqkVsCEMSyr7QqzsYMdbeGxEViuvgxhp3x6Fy9jIRz4kNdYJvzFUU="

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: 7.0
  allow_failures:
    # While teapot will run on these versions, let's not let them break builds.
    - php: 5.3
    - php: 5.4
    - php: 5.5
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
# Remove xdebug as per https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist

script:
  - bin/phpcs --standard=phpcs.xml src
  - bin/phpspec run --no-code-generation --format=pretty
...
